# Force rebuild 1
providers = ["node"]

[variables]
PATH = "/opt/venv/bin:$PATH"

[phases.setup]
nixPkgs = ["nodejs", "python311", "python311Packages.pip"]

[phases.install]
cmds = [
    "npm install",
    "pip install -r requirements.txt"
]

[start]
cmd = "node server.js"