# Force rebuild 1
providers = ["node"]

[variables]
PATH = "/opt/venv/bin:$PATH"

[phases.setup]
nixPkgs = ["nodejs", "python311"]

[phases.install]
cmds = [
    "npm install",
    "python3 -m venv /opt/venv",
    "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "node server.js"

